### ISSUE TITLE
Nothing against C++, but…

### ISSUE THREAD

**Issue by thgaskell** [hicapacity/bruddahbot#3]
Maybe there should be a check to see if the username exists in the slack workspace before awarding points? 😂 

![image](https://user-images.githubusercontent.com/844945/81349432-ad2c3280-905b-11ea-9152-856a93c036ac.png)
![image](https://user-images.githubusercontent.com/844945/81349462-b917f480-905b-11ea-85d9-4b0b5cf3d812.png)

**Comment by bmatcuk** [comment]
I don't think there's a way to check if usernames exist, but I added a couple lines so bruddahbot will ignore "c++"
